### ISSUE TITLE
How do European typists align their fingers?

### ISSUE THREAD

**Issue by pkamb** [kennetchaz/symmetric-typing#1]
Hi, I very much agree with your "symmetric typing" finger layout. I fell into this layout naturally when teaching myself to type (Dvorak) in 10th grade, as it is by far the most comfortable option on a standard keyboard. Probably helped that I had no official keyboard diagram to consult.

I also wrote that article on my One-Hand Keyboard site which I think you have read and linked to. Still gets frequent comments. I have meaning to update/expand on it.

The thing that has always been funny to me about the standard/uncomfortable `QAZ` fingering is how lazy it is. It's as if some typing teaching looked at the left-most row of keys and paired it with the left-most finger, wrist angles be damned.

If that scenario is true, I would expect European typists to be taught a symmetrical layout due to the undersized Left Shift key. The left-most rows here are `AQ<` and `ZSW`, which correspond to `QA-Shift` and `WSZ` on QWERTY.

![azerty](https://cloud.githubusercontent.com/assets/342355/9482163/ffe90f12-4b45-11e5-8c3f-e96b79588607.png)

This would apply to AZERTY and QWERTZ, perhaps amongst others.

I think it would be interesting to investigate typing instructions in European nations that use the small-shift-key layouts.

**Comment by kennetchaz** [comment]
Hi Peter,

Thanks for your comments, it is indeed odd how the "standard" system is so
prevalent yet largely unquestioned.
Part of the motivation for creating the site was that there seemed to be
very few mentions of this system, except in specialist keyboarding forums.
For example, I never seen a online typing tutorial that recommends it.
For European typists they can easily use their left pinky for that extra
key, but as far as am aware, the uncomfortable qaz fingering is taught
universally. I suspect in practise a lot of people actually use the
"symmetric" system without realizing, esp if they have not been formally
"taught".
