### ISSUE TITLE
Old Solemak layout 

### ISSUE THREAD

**Issue by EmadAlblueshi** [kennetchaz/symmetric-typing#4]
Hi,

I simply noticed that you have changed your layout to something different than below 

![484A7AE4-92B7-4D27-9F71-39BE97824342-16356-000009693873E1B3](https://user-images.githubusercontent.com/6061055/82106285-a6bb4c00-9728-11ea-9465-65ecb1c5b42e.PNG)

I simply switched  **P** with **H** and really happy with the results but little bit carious to know why did you change that layout in the website ?

Thanks

**Comment by kennetchaz** [comment]
I seem to have missed this question, but let me come back to answer it now:

The new version avoids some difficult bigrams like OK and PH with the layout above, and avoid having to move :; to an unusual location. 

The overall objective is the same though: a Colemak-like layout with "symmetric typing" built-in, while also minimizing unnecessary changes from Qwerty.
