### ISSUE TITLE
Preset on Patorik

### ISSUE THREAD

**Issue by ShalokShalom** [kennetchaz/symmetric-typing#5]
http://patorjk.com/keyboard-layout-analyzer/#/config

You show the heatmap from this homepage on your side - thanks, very helpful - and I struggled to find it commited on his page - did you do that and did I just miss it?

(See: preset)

**Comment by kennetchaz** [comment]
It's not one of the preset keyboards built-in to the patorjk.com analyzer unfortunately. However it is available on [this fork](https://stevep99.github.io/keyboard-layout-analyzer/#/mainhttps://stevep99.github.io/keyboard-layout-analyzer/#/main).
