### ISSUE TITLE
Mac downloads?

### ISSUE THREAD

**Issue by handcoding** [kennetchaz/symmetric-typing#7]
The Soul and Niro keyboard layouts look super interesting, and I’m thinking about trying them. But by chance might there be Mac downloads available for these layouts?

**Comment by kennetchaz** [comment]
There aren't currently, but if anyone reading this wants to contribute them, that would be great!

**Comment by JustAnOkapi** [comment]
Related to #9

**Comment by kennetchaz** [comment]
Mac contribution has been merged!
